import { useEffect, useMemo, useState } from "react";
import { normalizeNepalPhone } from "@/lib/phone";
import { responders as initialResponders, seedIncidents } from "@/data/seed";
import type { Incident, PriorityLevel, Responder, TranscriptLine } from "@/types/incident";

const lc: Record<PriorityLevel,string>={STANDARD:"standard",ELEVATED:"elevated",URGENT:"urgent","CRITICAL REVIEW":"critical"};
const yn=(v:boolean|null)=>v===null?"UNKNOWN":v?"YES":"NO";
const num=(v:number|null)=>v===null?"UNKNOWN":String(v);

export function CommandDashboard(){
 const [incidents,setIncidents]=useState(seedIncidents),[selectedId,setSelectedId]=useState(1042),[teams,setTeams]=useState(initialResponders);
 const [tab,setTab]=useState<"INTELLIGENCE"|"TRANSCRIPT">("INTELLIGENCE"),[mode,setMode]=useState<"LIVE"|"DEMO">("DEMO");
 const [phone,setPhone]=useState("9812345678"),[call,setCall]=useState<"IDLE"|"CALLING"|"CONNECTED"|"FAILED">("IDLE"),[error,setError]=useState(""),[step,setStep]=useState(0);
 const selected=incidents.find(i=>i.id===selectedId)??incidents[0];
 const metrics=useMemo(()=>({open:incidents.filter(i=>i.status!=="RESOLVED").length,urgent:incidents.filter(i=>i.priorityScore>=50).length,available:teams.filter(t=>t.status==="AVAILABLE").length}),[incidents,teams]);
 async function startCall(){setError("");const normalized=normalizeNepalPhone(phone);if(!normalized){setError("Enter a valid Nepal mobile number (98XXXXXXXX).");return}if(call==="CALLING"||call==="CONNECTED")return;if(mode==="LIVE"){setCall("CALLING");try{const r=await fetch("/api/calls/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phoneNumber:normalized})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Call could not be started")}catch(e){setCall("FAILED");setError(e instanceof Error?e.message:"Call failed")}return}setCall("CALLING");setStep(1);setSelectedId(1042);setTab("TRANSCRIPT");setTimeout(()=>{setCall("CONNECTED");setStep(2)},900)}
 useEffect(()=>{if(mode!=="DEMO"||call!=="CONNECTED"||step!==2)return;const t=[setTimeout(()=>setStep(3),1100),setTimeout(()=>setStep(4),2600),setTimeout(()=>setStep(5),4100),setTimeout(()=>setStep(6),5600)];return()=>t.forEach(clearTimeout)},[mode,call,step]);
 const transcript=selected.id===1042&&step>0?selected.transcript.slice(0,Math.max(0,step-1)):selected.transcript;
 function assign(team:Responder){setTeams(ts=>ts.map(t=>t.id===team.id?{...t,status:"ASSIGNED"}:t));setIncidents(xs=>xs.map(i=>i.id===selected.id?{...i,assignedTeam:team.name,status:"TEAM ASSIGNED"}:i))}
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><div className="brandmark">र</div><div><strong>RAKSHA AI</strong><span>Flood Emergency Command Center</span></div></div><div className="system"><i/> SYSTEM ONLINE <small>All services operational</small></div><div className="mode-switch"><button className={mode==="LIVE"?"active":""} onClick={()=>setMode("LIVE")}>LIVE</button><button className={mode==="DEMO"?"active":""} onClick={()=>setMode("DEMO")}>DEMO</button></div><div className="operator"><span>SC</span><div><b>Command Operator</b><small>Kathmandu Center</small></div></div></header>
  {mode==="DEMO"&&<div className="simulation-banner"><b>SIMULATION MODE</b><span>All incidents and call activity shown are simulated for demonstration.</span></div>}
  <section className="metrics"><Metric label="ACTIVE CALLS" value={call==="CONNECTED"?1:0} meta={call==="CONNECTED"?"1 connected":"No current calls"}/><Metric label="OPEN INCIDENTS" value={metrics.open} meta="Across Nepal"/><Metric label="URGENT CASES" value={metrics.urgent} meta="Requires attention" alert/><Metric label="AVAILABLE TEAMS" value={metrics.available} meta={`${teams.length} total teams`}/></section>
  <section className="workspace">
   <aside className="queue panel"><div className="panel-title"><div><p>INCIDENT QUEUE</p><span>{metrics.open} OPEN CASES</span></div><button>≡</button></div><div className="queue-list">{incidents.map(i=><button key={i.id} className={`incident-card ${selectedId===i.id?"selected":""}`} onClick={()=>setSelectedId(i.id)}><div className="incident-top"><b>#{i.id}</b><span className={`badge ${lc[i.priorityLevel]}`}>{i.priorityLevel}</span></div><h3><span>●</span>{i.location.rawText??"Location unknown"}</h3><div className="facts"><span><b>{num(i.peopleCount)}</b> PEOPLE</span><span><b>{yn(i.trapped)}</b> TRAPPED</span></div><div className="incident-foot"><span>{i.simulated?"SIMULATION":"LIVE"}</span><time>{i.id===1042?"2 MIN AGO":"8 MIN AGO"}</time></div></button>)}</div></aside>
   <section className="center-column"><CallPanel mode={mode} phone={phone} setPhone={setPhone} state={call} error={error} onCall={startCall} transcript={transcript}/><MapPanel incidents={incidents} selectedId={selectedId} onSelect={setSelectedId}/></section>
   <aside className="intelligence panel"><div className="detail-head"><div><p>INCIDENT INTELLIGENCE</p><h2>INCIDENT #{selected.id}</h2></div><span className={`badge ${lc[selected.priorityLevel]}`}>{selected.priorityLevel}</span></div><div className="tabs"><button className={tab==="INTELLIGENCE"?"active":""} onClick={()=>setTab("INTELLIGENCE")}>INTELLIGENCE</button><button className={tab==="TRANSCRIPT"?"active":""} onClick={()=>setTab("TRANSCRIPT")}>TRANSCRIPT</button></div>
   {tab==="TRANSCRIPT"?<Transcript lines={transcript}/>:<div className="detail-scroll"><section className="location-block"><small>REPORTED LOCATION</small><b>{selected.location.rawText??"Unknown"}</b><span>{selected.location.accuracy} • {selected.location.district??"District unknown"}</span></section><section><Label>LIVE EXTRACTION</Label><div className="data-grid"><Data label="People" value={num(selected.peopleCount)}/><Data label="Trapped" value={yn(selected.trapped)} warn={selected.trapped===true}/><Data label="Can evacuate" value={yn(selected.canEvacuate)} warn={selected.canEvacuate===false}/><Data label="Injuries" value={selected.seriousInjury===null?"UNKNOWN":selected.seriousInjury?"SERIOUS":"NONE"}/><Data label="Children" value={num(selected.childrenCount)}/><Data label="Elderly" value={num(selected.elderlyCount)}/><Data label="Mobility" value={yn(selected.mobilityImpaired)} warn={selected.mobilityImpaired===true}/><Data label="Water rising" value={yn(selected.waterRising)} warn={selected.waterRising===true}/></div></section><section><Label>AI SITUATION SUMMARY</Label><p className="summary">{selected.summary}</p></section><section className="priority-box"><div className="score-ring"><b>{selected.priorityScore}</b><span>SCORE</span></div><div><small>DETERMINISTIC PRIORITY</small><h3>{selected.priorityLevel}</h3><p>Decision support • Human review required</p></div></section><section><Label>WHY THIS PRIORITY?</Label><ul className="reasons">{selected.priorityReasons.length?selected.priorityReasons.map(r=><li key={r}>✓ {r}</li>):<li>No elevated risk factors confirmed.</li>}</ul></section>{selected.evidence.length>0&&<section><Label>EVIDENCE</Label>{selected.evidence.map(e=><details className="evidence" key={e.field}><summary>{e.field.replaceAll("_"," ")} <span>{Math.round(e.confidence*100)}%</span></summary><q>{e.quote}</q></details>)}</section>}<section><Label>RECOMMENDED RESPONSE</Label><div className="recommendations">{selected.recommendedResponse.map(r=><span key={r}>{r}</span>)}</div></section><section><Label>HUMAN RESPONSE</Label>{selected.assignedTeam?<div className="assigned">✓ {selected.assignedTeam}<small>TEAM ASSIGNED</small></div>:<div className="team-list">{teams.filter(t=>t.status==="AVAILABLE").slice(0,3).map(t=><button key={t.id} onClick={()=>assign(t)}><span>{t.name}<small>{t.type}</small></span><b>ASSIGN</b></button>)}</div>}</section></div>}
   <div className="actions"><button>ADD NOTE</button><button>CALL BACK</button><button className="resolve" onClick={()=>setIncidents(xs=>xs.map(i=>i.id===selected.id?{...i,status:"RESOLVED"}:i))}>RESOLVE</button></div></aside>
  </section>
 </main>
}

function Metric({label,value,meta,alert}:{label:string;value:number;meta:string;alert?:boolean}){return <div className="metric"><span className={alert?"metric-icon alert":"metric-icon"}>{alert?"!":"•"}</span><div><small>{label}</small><b>{String(value).padStart(2,"0")}</b></div><p>{meta}</p></div>}
function Label({children}:{children:React.ReactNode}){return <h4 className="section-label">{children}</h4>}
function Data({label,value,warn}:{label:string;value:string;warn?:boolean}){return <div><small>{label}</small><b className={warn?"warn":""}>{value}</b></div>}
function Transcript({lines}:{lines:TranscriptLine[]}){return <div className="transcript">{lines.length===0?<div className="empty">WAITING FOR TRANSCRIPT</div>:lines.map(l=><div className={`line ${l.speaker.toLowerCase()}`} key={l.id}><div><b>{l.speaker}</b><time>{l.time}</time></div><p>{l.text}</p></div>)}</div>}
function CallPanel({mode,phone,setPhone,state,error,onCall,transcript}:{mode:string;phone:string;setPhone:(v:string)=>void;state:string;error:string;onCall:()=>void;transcript:TranscriptLine[]}){const active=state==="CONNECTED"||state==="CALLING";return <section className={`call-panel panel ${active?"live":""}`}><div className="call-title"><div><span className="phone-icon">☎</span><div><p>{active?"LIVE CALL":"CALL A VICTIM"}</p><b>{active?"+977 98****678":"Start an AI-assisted emergency call"}</b></div></div>{active&&<span className="live-pill"><i/> {state}</span>}</div>{!active?<div className="call-form"><label><small>COUNTRY</small><span>🇳🇵 Nepal <b>+977</b></span></label><label className="number"><small>MOBILE NUMBER</small><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98XXXXXXXX"/></label><button onClick={onCall}>{state==="FAILED"?"TRY AGAIN":"CALL WITH RAKSHA"} →</button>{error&&<p className="form-error">{error}</p>}</div>:<div className="call-live"><div className="wave">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${8+(i*13%24)}px`}}/>)}</div><div><b>{state==="CALLING"?"CONNECTING TO VICTIM…":"RAKSHA IS LISTENING"}</b><span>{mode==="DEMO"?"SIMULATED CALL":"LIVE PROVIDER CALL"} • 00:42</span></div><button>■</button></div>}{active&&transcript.length>0&&<div className="latest-line"><b>{transcript.at(-1)?.speaker}</b><span>“{transcript.at(-1)?.text}”</span></div>}</section>}
function MapPanel({incidents,selectedId,onSelect}:{incidents:Incident[];selectedId:number;onSelect:(id:number)=>void}){const [zoom,setZoom]=useState(1),xy=(lat:number,lng:number)=>({x:((lng-80)/8.3)*100,y:(1-(lat-26.2)/4.3)*100});return <section className="map-panel panel"><div className="map-head"><div><p>LIVE INCIDENT MAP</p><span><i/> {incidents.length} INCIDENTS MAPPED</span></div><button onClick={()=>setZoom(1)}>FIT TO INCIDENTS</button></div><div className="map-canvas"><div className="terrain" style={{transform:`scale(${zoom})`}}><svg viewBox="0 0 800 390" preserveAspectRatio="none"><path className="country" d="M42 226 L90 203 139 211 189 183 238 190 288 156 340 172 391 135 450 149 505 111 558 124 612 88 681 102 741 71 766 100 726 126 680 131 633 158 580 151 531 180 478 174 428 210 374 198 323 232 269 220 214 252 160 240 108 260 57 246 Z"/><path className="river" d="M120 210 Q250 130 380 205 T700 115"/><path className="road" d="M70 235 Q230 215 360 180 T735 100"/></svg>{incidents.filter(i=>i.location.latitude!==null).map(i=>{const p=xy(i.location.latitude!,i.location.longitude!);return <button key={i.id} onClick={()=>onSelect(i.id)} className={`map-marker ${lc[i.priorityLevel]} ${selectedId===i.id?"active":""}`} style={{left:`${p.x}%`,top:`${p.y}%`}}><span>{i.priorityScore}</span>{selectedId===i.id&&<div className="map-popup"><b>INCIDENT #{i.id}</b><strong>{i.location.rawText}</strong><small>{num(i.peopleCount)} PEOPLE • TRAPPED {yn(i.trapped)}</small><em>{i.priorityLevel}</em></div>}</button>})}</div><div className="map-tools"><button onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>+</button><button onClick={()=>setZoom(z=>Math.max(.8,z-.1))}>−</button></div><div className="map-legend"><span className="standard">● Standard</span><span className="elevated">● Elevated</span><span className="urgent">● Urgent</span><span className="critical">● Critical</span></div><small className="map-credit">SIMULATED MAP • COORDINATES APPROXIMATE</small></div></section>}
